name: Auto Deployment

on:
  push:
   branches:
      - 'master'

jobs:
  Deploy-to-Master:

    runs-on: ubuntu-latest

    steps:
    - name: SSH into server and perform git operations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BBIL_IP }}
        username: 'root'
        key: ${{ secrets.BBIIL }}
        port: '22'
        script: |
          cd /var/www/nasa/webbner/ && git pull origin main
